# Generated by Django 4.1.10 on 2024-03-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_sub_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funfact',
            name='funfact_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='header',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='largebox',
            name='box_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='test_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='test_post',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='test_subject',
            field=models.CharField(max_length=50),
        ),
    ]
