# Generated by Django 4.1.10 on 2024-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_box_box_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='exp_title',
        ),
        migrations.AddField(
            model_name='content',
            name='img1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='content',
            name='img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
