# Generated by Django 4.1.10 on 2024-03-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_boxicon_largeboximage_delete_box_delete_largebox_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxicon',
            old_name='box_icon',
            new_name='box_icon1',
        ),
        migrations.RenameField(
            model_name='largeboximage',
            old_name='box_icon',
            new_name='box_icon1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_img',
            new_name='project_img1',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='logo',
            new_name='logo1',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='logo_hover',
            new_name='logo2',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='test_img',
            new_name='test_img1',
        ),
        migrations.AddField(
            model_name='boxicon',
            name='box_icon2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='boxicon',
            name='box_icon3',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='content',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='largeboximage',
            name='box_icon2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='largeboximage',
            name='box_icon3',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_img2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_img3',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_img4',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo3',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo4',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo5',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo6',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo7',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo8',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo9',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover1',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover3',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover4',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover5',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover6',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover7',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover8',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='logo_hover9',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='test_img2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='test_img3',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='test_img4',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
