# Generated by Django 4.1.10 on 2024-03-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_box_heading_boxicon_box_heading1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funfact',
            old_name='funfact_text',
            new_name='funfact_text1',
        ),
        migrations.RenameField(
            model_name='funfact',
            old_name='funfact_title',
            new_name='funfact_title1',
        ),
        migrations.RemoveField(
            model_name='funfact',
            name='funfact_count',
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_count1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_count2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_count3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_count4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_text4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_title2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_title3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funfact',
            name='funfact_title4',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
