# Generated by Django 4.1.10 on 2024-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_funfact_text_funfact_funfact_text1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='boxicon',
            name='sub_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxicon',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
