# Generated by Django 4.1.10 on 2024-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_section_boxicon_sub_title_boxicon_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('sub_heading', models.CharField(max_length=500)),
                ('location1', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=200)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.CharField(default='+91 0000000000', max_length=15)),
                ('location2', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=200)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.CharField(default='+91 0000000000', max_length=15)),
                ('location3', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=200)),
                ('email3', models.EmailField(max_length=254)),
                ('phone3', models.CharField(default='+91 0000000000', max_length=15)),
            ],
        ),
    ]
