# Generated by Django 4.1.10 on 2024-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading1', models.CharField(max_length=100)),
                ('text1', models.CharField(max_length=200)),
                ('img2', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading2', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=200)),
                ('img3', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading3', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=200)),
                ('img4', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading4', models.CharField(max_length=100)),
                ('text4', models.CharField(max_length=200)),
                ('img5', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading5', models.CharField(max_length=100)),
                ('text5', models.CharField(max_length=200)),
                ('img6', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading6', models.CharField(max_length=100)),
                ('text6', models.CharField(max_length=200)),
            ],
        ),
    ]
