# Generated by Django 4.1.10 on 2024-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('text', models.CharField(max_length=100)),
                ('phone_heading', models.CharField(max_length=100)),
                ('phone', models.CharField(default='+91 0000000000', max_length=15)),
                ('email_heading', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
