# Generated by Django 4.1.10 on 2024-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
    ]
