# Generated by Django 4.1.10 on 2024-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_banner_price_security_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='success',
            name='sub_heading',
            field=models.CharField(max_length=500),
        ),
    ]
