# Generated by Django 4.1.10 on 2024-03-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_success_heading_alter_success_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='plan1_currency',
            field=models.CharField(default='$', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_list_item1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_list_item2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_list_item3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan1_yearly_price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_currency',
            field=models.CharField(default='$', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_list_item1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_list_item2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_list_item3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_list_item4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan2_yearly_price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_currency',
            field=models.CharField(default='$', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_list_item1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_list_item2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_list_item3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_period',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='plan3_yearly_price',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='sub_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
