# Generated by Django 4.1.10 on 2024-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='test_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='test_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='test_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='test_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='boxicon',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='boxicon',
            name='title',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='exp_heading',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='exp_text',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='exp_year',
        ),
        migrations.AddField(
            model_name='content',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='experience',
            name='question',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='question_no',
            field=models.IntegerField(default=1),
        ),
    ]
