# Generated by Django 4.1.10 on 2024-03-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_img_content_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sub_heading',
        ),
    ]
