# Generated by Django 4.1.10 on 2024-03-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_contact_heading_remove_contact_sub_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='price',
            name='title',
        ),
        migrations.RemoveField(
            model_name='security',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='success',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='success',
            name='sub_heading',
        ),
    ]
