# Generated by Django 4.1.10 on 2024-03-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_contactus_delete_contacts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
