# Generated by Django 4.1.10 on 2024-03-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_experience_company_alter_advice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'verbose_name': 'Advice', 'verbose_name_plural': 'Advices'},
        ),
        migrations.AlterModelOptions(
            name='monthly_price',
            options={'verbose_name': 'Monthly_Price', 'verbose_name_plural': 'Monthly_Prices'},
        ),
        migrations.AlterModelOptions(
            name='yearly_price',
            options={'verbose_name': 'Yearly_Price', 'verbose_name_plural': 'Yearly_Prices'},
        ),
    ]
