# Generated by Django 4.1.10 on 2024-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_advice_options_alter_monthly_price_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('logo_hover', models.FileField(blank=True, null=True, upload_to='gallery')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='logo_hover',
        ),
        migrations.AddField(
            model_name='slider',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
