# Generated by Django 4.1.10 on 2024-03-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_gallery_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'DownMember',
                'verbose_name_plural': 'DownMembers',
            },
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('member1', models.CharField(max_length=100)),
                ('member2', models.CharField(max_length=100)),
                ('member3', models.CharField(max_length=100)),
                ('member4', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MemberList',
                'verbose_name_plural': 'MemberLists',
            },
        ),
        migrations.CreateModel(
            name='TopMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TopMember',
                'verbose_name_plural': 'TopMembers',
            },
        ),
    ]
