# Generated by Django 4.1.10 on 2024-03-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_downmember_memberlist_topmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('logo_hover', models.FileField(blank=True, null=True, upload_to='gallery')),
            ],
            options={
                'verbose_name': 'AboutUsBrand',
                'verbose_name_plural': 'AboutUsBrands',
            },
        ),
        migrations.CreateModel(
            name='AboutUsFunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'AboutUsFunFact',
                'verbose_name_plural': 'AboutUsFunFacts',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='AboutUsSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'AboutUsSolution',
                'verbose_name_plural': 'AboutUsSolutions',
            },
        ),
        migrations.CreateModel(
            name='AboutUsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'AboutUsStory',
                'verbose_name_plural': 'AboutUsStories',
            },
        ),
        migrations.CreateModel(
            name='AboutUsTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'AboutUsTestimonial',
                'verbose_name_plural': 'AboutUsTestimonials',
            },
        ),
    ]
