# Generated by Django 4.1.10 on 2024-03-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_brands_name_alter_aboutusbrand_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('heading', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='ProgressChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'ProgressChart',
                'verbose_name_plural': 'ProgressCharts',
            },
        ),
        migrations.RemoveField(
            model_name='brands',
            name='name',
        ),
        migrations.AlterField(
            model_name='aboutusbrand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='aboutusbrand',
            name='logo_hover',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='aboutusstory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='aboutustestimonial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='boxicon',
            name='box_icon',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='logo_hover',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='downmember',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='largeboximage',
            name='box_icon',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='monthly_price',
            name='plan_img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='topmember',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='yearly_price',
            name='plan_img',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
