# Generated by Django 4.1.10 on 2024-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_testimonials_testimonialpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsBrand',
        ),
        migrations.DeleteModel(
            name='AboutUsFunFact',
        ),
        migrations.DeleteModel(
            name='AboutUsTestimonial',
        ),
        migrations.DeleteModel(
            name='DownMember',
        ),
        migrations.DeleteModel(
            name='LargeBoxImage',
        ),
        migrations.DeleteModel(
            name='Monthly_Price',
        ),
        migrations.DeleteModel(
            name='TestimonialPage',
        ),
        migrations.DeleteModel(
            name='TopMember',
        ),
        migrations.DeleteModel(
            name='Yearly_Price',
        ),
        migrations.AddField(
            model_name='boxicon',
            name='page',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brands',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutusstory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='about_us/gallery'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='advices/gallery'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='banner/gallery'),
        ),
        migrations.AlterField(
            model_name='boxicon',
            name='box_icon',
            field=models.FileField(blank=True, null=True, upload_to='boxes/gallery'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='brands/gallery'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='logo_hover',
            field=models.FileField(blank=True, null=True, upload_to='brands/gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='gallery/gallery'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.FileField(blank=True, null=True, upload_to='projects/gallery'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='services/gallery'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='slider/gallery'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='slider/gallery'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/gallery'),
        ),
    ]
