# Generated by Django 4.1.10 on 2024-03-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_delete_aboutusbrand_delete_aboutusfunfact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsStory',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='boxicon',
            name='project_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
