# Generated by Django 4.1.10 on 2024-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_aboutusstory_delete_banner_delete_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxicon',
            old_name='box_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='boxicon',
            old_name='box_icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='boxicon',
            old_name='box_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='boxicon',
            name='project_category',
        ),
        migrations.AddField(
            model_name='gallery',
            name='page',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
