# Generated by Django 4.1.10 on 2024-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_box_heading_boxicon_heading_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Security',
        ),
        migrations.AddField(
            model_name='success',
            name='page',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutussolution',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='success',
            name='text',
            field=models.TextField(),
        ),
    ]
