# Generated by Django 4.1.10 on 2024-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_delete_security_success_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='slider',
            name='heading',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='page',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
