from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Slider)
admin.site.register(Brands)
admin.site.register(BoxIcon)
admin.site.register(Company)
admin.site.register(LargeBoxImage)
admin.site.register(FunFact)
admin.site.register(Project)
admin.site.register(Testimonial)
admin.site.register(ContactUs)
admin.site.register(Service)
admin.site.register(Advice)
admin.site.register(Banner)
admin.site.register(Success)
admin.site.register(Security)
admin.site.register(Monthly_Price)
admin.site.register(Yearly_Price)
admin.site.register(Jobs)
admin.site.register(Gallery)
admin.site.register(TopMember)
admin.site.register(DownMember)
admin.site.register(MemberList)
admin.site.register(AboutUsStory)
admin.site.register(AboutUsSolution)
admin.site.register(AboutUsFunFact)
admin.site.register(AboutUsTestimonial)
admin.site.register(AboutUsBrand)
